name: DockerHub Workflow

on:
  push:
    branches:
      - workflow

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_TOBI }}
          password: ${{ secrets.DOCKERHUB_TOKEN_TOBI }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_THEOLA }}
          password: ${{ secrets.DOCKERHUB_TOKEN_THEOLA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: rventory/image:latest